name: 'Codepipeline Webhook Action'
description: 'Codepipeline Webhook Action'
inputs:
  name:
    description: 'Name of the pipeline to trigger'
    required: true
  region:
    description: 'AWS Region'
    required: true
  aws_account_id:
    description: 'AWS Account ID'
    required: true
  codepipeline_webhook_secret:
    description: 'API Key of the Webhook that triggers code pipeline'
    required: true
  codepipeline_webhook_url:
    description: 'Codepipeline Webhook URL'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
